"""cria tabela documents sprint 13

Revision ID: 098dadecccce
Revises: 4c5538cffadb
Create Date: 2026-02-05 16:54:49.232149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098dadecccce'
down_revision: Union[str, Sequence[str], None] = '4c5538cffadb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_company_owner', 'users', ['owner_id'], ['id'], use_alter=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint('fk_company_owner', type_='foreignkey')

    # ### end Alembic commands ###
