"""sprint_15_remodelagem_completa

Revision ID: 1a7e2c26c182
Revises: 098dadecccce
Create Date: 2026-02-11 13:21:50.952674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a7e2c26c182'
down_revision: Union[str, Sequence[str], None] = '098dadecccce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_company_links',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'company_id')
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inscricao_estadual', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('inscricao_municipal', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('numero', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('complemento', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cidade', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('telefone', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email_corporativo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('responsavel_nome', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('responsavel_cpf', sa.String(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('rg', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('celular', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('genero', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_cpf'), ['cpf'], unique=True)
        batch_op.drop_constraint(batch_op.f('users_company_id_fkey'), type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('users_company_id_fkey'), 'companies', ['company_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_users_cpf'))
        batch_op.drop_column('genero')
        batch_op.drop_column('celular')
        batch_op.drop_column('rg')
        batch_op.drop_column('cpf')

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('responsavel_cpf')
        batch_op.drop_column('responsavel_nome')
        batch_op.drop_column('email_corporativo')
        batch_op.drop_column('whatsapp')
        batch_op.drop_column('telefone')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cep')
        batch_op.drop_column('inscricao_municipal')
        batch_op.drop_column('inscricao_estadual')

    op.drop_table('user_company_links')
    # ### end Alembic commands ###
