"""initial_structure_and_certificates

Revision ID: 56183831685d
Revises: 
Create Date: 2026-02-03 13:26:30.170177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56183831685d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('certificate_type', sa.String(), nullable=False),
    sa.Column('control_code', sa.String(), nullable=True),
    sa.Column('issuing_body', sa.String(), nullable=True),
    sa.Column('emission_date', sa.Date(), nullable=False),
    sa.Column('expiration_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_certificates_expiration_date'), ['expiration_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_certificates_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_expiration_date'))

    op.drop_table('certificates')
    # ### end Alembic commands ###
