"""Add flags table company

Revision ID: 70ff9ef8c30f
Revises: 1611e597787c
Create Date: 2026-02-13 16:11:05.466517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ff9ef8c30f'
down_revision: Union[str, Sequence[str], None] = '1611e597787c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_contract_signed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_payment_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_admin_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('is_admin_verified')
        batch_op.drop_column('is_payment_active')
        batch_op.drop_column('is_contract_signed')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
