"""add_document_id_to_certificates

Revision ID: 9b79507a85a6
Revises: 9e673d7d2896
Create Date: 2026-02-19 11:24:13.086352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b79507a85a6'
down_revision: Union[str, Sequence[str], None] = '9e673d7d2896'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['document_id'])
        batch_op.create_foreign_key(None, 'documents', ['document_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###
