"""create_certificate_structure

Revision ID: 9e673d7d2896
Revises: 70ff9ef8c30f
Create Date: 2026-02-17 15:18:31.435335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e673d7d2896'
down_revision: Union[str, Sequence[str], None] = '70ff9ef8c30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_categories_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_categories_slug'), ['slug'], unique=True)

    op.create_table('document_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('validity_days_default', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['document_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_types_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_types_slug'), ['slug'], unique=True)

    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('type_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('file_path', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('authentication_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('issue_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('metadata_info', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.alter_column('expiration_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('certificates_document_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_certificates_authentication_code'), ['authentication_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_certificates_type_id'), ['type_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('certificates_document_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'companies', ['company_id'], ['id'])
        batch_op.create_foreign_key(None, 'document_types', ['type_id'], ['id'])
        batch_op.drop_column('emission_date')
        batch_op.drop_column('issuing_body')
        batch_op.drop_column('control_code')
        batch_op.drop_column('certificate_type')
        batch_op.drop_column('document_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('certificate_type', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('control_code', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('issuing_body', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('emission_date', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('certificates_document_id_fkey'), 'documents', ['document_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_certificates_type_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_status'))
        batch_op.drop_index(batch_op.f('ix_certificates_company_id'))
        batch_op.drop_index(batch_op.f('ix_certificates_authentication_code'))
        batch_op.create_unique_constraint(batch_op.f('certificates_document_id_key'), ['document_id'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('expiration_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('metadata_info')
        batch_op.drop_column('status')
        batch_op.drop_column('issue_date')
        batch_op.drop_column('authentication_code')
        batch_op.drop_column('filename')
        batch_op.drop_column('file_path')
        batch_op.drop_column('type_id')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('document_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_types_slug'))
        batch_op.drop_index(batch_op.f('ix_document_types_id'))

    op.drop_table('document_types')
    with op.batch_alter_table('document_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_categories_slug'))
        batch_op.drop_index(batch_op.f('ix_document_categories_id'))

    op.drop_table('document_categories')
    # ### end Alembic commands ###
